### ISSUE TITLE
Documentation state: intern or extern?

### ISSUE THREAD

**Issue by maiste** [maiste/eos#57]
As I'm working on the Eos documentation, I was wondering if we prefer to centralize the documentation along the project development docs or if we prefer to extract the documentation outside of the repo?

My first guess is to keep it here and well structure the `mkdocs` in several parts:
 - header writer documentation
 - user documentation
 - dev documentation

What is your point of view on that @xavitator? Also, I've decided to move to `mkdocs` and not `sphinx` because I find it easier to maintain.

**Comment by xavitator** [comment]
I agree with you. I think it is more understandable to do like it.
What do you think about auto generate dev doc with doxygen or something like?

**Comment by maiste** [comment]
Nice! I keep it this way so.

We already support the documentation generation for the developer part with `odoc` and `dune`. You just have to run `dune build @doc` and it will produce it.

I might add a `Makefile` in the future to summarize this kind of actions. I have already created a documentation page on readthedocs which automatically builds it from the source directory with `mkdocs`.

You can check it there: https://eos-hm.readthedocs.io/en/master.

**Comment by xavitator** [comment]
Ohh, yes, sorry, I forget it!
I think that a makefile is too similar to dune script, and it will be useless 🤔

**Comment by maiste** [comment]
That what I thought first, but in fact it's pretty convenient and common to wrap some commands with it.

**Comment by xavitator** [comment]
Okok, if you think it is easier 😉
